### ISSUE TITLE
KeyError: 'seq_num'

### ISSUE THREAD

**Issue by shulanmayo** [griffithlab/pVAC-Seq#269] opened 2017-02-21 00:17 UTC
We installed IEDB tools locally (2.15.3)  and edited the scripts to point to python 2.7 as in readtheDocs but getting following error message. Here is my command:
pvacseq run -e 8 -l 21 -b 500 -c 1 --iedb-install-directory iedb-mhc/ test.vep.vcf test "HLA-A*02:01,HLA-A*11:01,HLA-B*40:01,HLA-B*55:01,HLA-C*03:03,HLA-C*03:04" NetMHC testout
or this (with calling local DB)
pvacseq run -e 8 -l 21 -b 500 -c 1 test.vep.vcf test "HLA-A*02:01,HLA-A*11:01,HLA-B*40:01,HLA-B*55:01,HLA-C*03:03,HLA-C*03:04" NetMHC testout

Both gave the following errors:

Processing entries for Allele HLA-A*02:01 and Epitope Length 8 - Entries 1-200
IEDB file for Allele HLA-A*02:01 and Epitope Length 8 with Method NetMHC (Entries 1-200) already exists. Skipping.
Parsing IEDB Output for Allele HLA-A*02:01 and Epitope Length 8 - Entries 1-200
Traceback (most recent call last):
  File "misc/python/3.5.2/bin/pvacseq_core", line 11, in <module>
    sys.exit(main())
  File "misc/python/3.5.2/lib/python3.5/site-packages/pvacseq/pvacseq.py", line 84, in main
    args[0].func.main(args[1])
  File "misc/python/3.5.2/lib/python3.5/site-packages/pvacseq/lib/main.py", line 285, in main
    pipeline.execute()
  File "misc/python/3.5.2/lib/python3.5/site-packages/pvacseq/lib/pipeline.py", line 253, in execute
    split_parsed_output_files = self.call_iedb_and_parse_outputs(chunks)
  File "misc/python/3.5.2/lib/python3.5/site-packages/pvacseq/lib/pipeline.py", line 391, in call_iedb_and_parse_outputs
    lib.parse_output.main(params)
  File "misc/python/3.5.2/lib/python3.5/site-packages/pvacseq/lib/parse_output.py", line 453, in main
    iedb_results = process_input_iedb_file(args.input_iedb_files, tsv_entries, args.key_file, args.top_result_per_mutation, args.top_score_metric)
  File "misc/python/3.5.2/lib/python3.5/site-packages/pvacseq/lib/parse_output.py", line 364, in process_input_iedb_file
    iedb_results              = parse_iedb_file(input_iedb_files, tsv_entries, key_file)
  File "misc/python/3.5.2/lib/python3.5/site-packages/pvacseq/lib/parse_output.py", line 230, in parse_iedb_file
    protein_label  = int(line['seq_num'])
KeyError: 'seq_num'

We did further test:
cat ./test_out/MHC_Class_I/tmp/test.ann.HLA-A\*02\:01.8.tsv_1-200 | head -10
started iedb
obtained arguments.
number of arguments:  4
allele	seq_num	start	end	length	peptide	ic50	rank
HLA-A*02:01	22	6	13	8	LLLLFMGL	596.86	0.6
HLA-A*02:01	21	6	13	8	LLLLFLGL	691.37	0.6
HLA-A*02:01	39	4	11	8	LLILLLQL	993.39	0.6
HLA-A*02:01	21	2	9	8	SLVPLLLL	998.14	0.6
HLA-A*02:01	22	2	9	8	SLVPLLLL	998.14	0.6
HLA-A*02:01	40	4	11	8	LLILLLQI	1087.91	0.7

cat ./test_out/MHC_Class_I/tmp/test. | head -10 test.ann.HLA-A*02:01.8.tsv_1-200         test.HLA-A*02:01.8.parsed.tsv_1-200.tmp  
[m108869@franklin01 MT2_MC_VAR_COMBINE]$ cat ./test_out/MHC_Class_I/tmp/test.HLA-A\*02\:01.8.parsed.tsv_1-200.tmp | head -10
Chromosome	Start	Stop	Reference	Variant	Transcript	Ensembl Gene ID	Variant Type	Mutation	Protein PositionGene Name	HLA Allele	Peptide Length	Sub-peptide Position	Mutation Position	MT Epitope Seq	WT Epitope Seq	Best MT Score Method	Best MT Score	Corresponding WT Score	Corresponding Fold Change	Tumor DNA Depth	Tumor DNA VAF	Tumor RNA Depth	Tumor RNA VAF	Normal Depth	Normal VAF	Gene Expression	Transcript Expression	Median MT Score	Median WT Score	Median Fold Change	NetMHC WT Score	NetMHC MT Score
wc -l ./test_out/MHC_Class_I/tmp/*
  132 ./test_out/MHC_Class_I/tmp/test_21.fa.split_1-200
  266 ./test_out/MHC_Class_I/tmp/test_21.fa.split_1-200.key
  104 ./test_out/MHC_Class_I/tmp/test_21.fa.split_201-316
  166 ./test_out/MHC_Class_I/tmp/test_21.fa.split_201-316.key
  940 ./test_out/MHC_Class_I/tmp/test.ann.HLA-A*02:01.8.tsv_1-200
    1 ./test_out/MHC_Class_I/tmp/test.HLA-A*02:01.8.parsed.tsv_1-200.tmp
 1609 total

I searched all issues and didn't find the same case. Any help will be greatly appreciated. thanks

**Comment by susannasiebert** [comment] 2017-02-21 14:47
Hm, that is certainly strange. Looks like a bug but it's not apparent to me what the source of the error is. What is the pVAC-Seq version that you have installed (`pvaseq -v`). The latest version is 4.0.6. If you have an older version installed could you try to update to the latest version and see if that fixes things? If you already have 4.0.6 installed, could you provide me with the vcf that resulted in this bug? You can attach it to this ticket or email it to pvacseq-support@genome.wustl.edu.

**Comment by kylec** [comment] 2017-02-21 17:15
I'm also getting a KeyError: 'seq_num' error. I'm using version 4.0.6. Below is the command I ran.
pvacseq run EBL7-EBL8.vep.vcf EBL7 HLA-A*25:01,HLA-A*02:01,HLA-B*08:01,HLA-B*18:01,HLA-C*12:03,HLA-C*07:01, NetMHC EBL7-result -e 8,9,10,11
[vcf.zip](https://github.com/griffithlab/pVAC-Seq/files/790887/vcf.zip)

**Comment by susannasiebert** [comment] 2017-02-22 19:27
@shulanmayo @kylec I was not able to recreate this error locally for either of your VCFs. One thing that might be happening is that you have an old output folder that you are reusing. The bugfix for this error involved some changes in how we create the tsv and fasta files. If you are rerunning on an output folder that already contains those files, they will not be recreated and still cause this error downstream. Could you please try and run your command on an empty output folder and see if that fixes things?

@kylec Running your VCF uncovered another unrelated bug so even when you run this VCF with an empty output directory you will see another error from IEDB ("ERROR: Input sequence is too short!"). A fix for this is forthcoming and will be part of the next release.

**Comment by shulanmayo** [comment] 2017-02-22 19:38
Hi Susanna,

Thanks for your time. I tried the command with empty output folder, and still get the same error. Could this be caused by any python modules (3.5 for main program and 2.7 for IEDB)? Even I don’t use

-- --iedb-install-directory /iedb-mhc/ \

It still gives the same error though.

Shulan

**Comment by susannasiebert** [comment] 2017-02-22 19:46
Ok, lets try reinstalling pvacseq. You can uninstall pvacseq with `pip uninstall pvacseq` and then reinstall with the `pip install pvacseq` command. And then try again with an empty output folder.

**Comment by shulanmayo** [comment] 2017-02-22 19:51
Thanks. I will ask IT to try this. Meanwhile. When I don’t use – local db, I got this. It seems there is hard code somewhere.

Executing MHC Class I predictions
Converting VCF to TSV
Completed
Splitting TSV into smaller chunks
Splitting TSV into smaller chunks - Entries 1-100
Splitting TSV into smaller chunks - Entries 101-158
Completed
Generating Variant Peptide FASTA and Key Files
Generating Variant Peptide FASTA and Key Files - Entries 1-200
Generating Variant Peptide FASTA and Key Files - Entries 201-316
Completed
Processing entries for Allele HLA-A*02:01 and Epitope Length 8 - Entries 1-200
Running IEDB on Allele HLA-A*02:01 and Epitope Length 8 with Method NetMHC - Entries 1-200
Error posting request to IEDB.
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>403 Forbidden</title>
</head><body>
<h1>Forbidden</h1>
<p>You don't have permission to access /tools_api/mhci/
on this server.</p>
<hr>
<address>Apache/2.4.6 (CentOS) Server at tools-cluster-interface.iedb.org Port 80</address>
</body></html>

**Comment by susannasiebert** [comment] 2017-02-22 19:54
We had this problem previously as well. In our case our IP address got blacklisted by IEDB because we made too many requests in a short time and overloaded their system. You will need to contact IEDB at help.iedb.org to remove your IP address from their blocked list. We are working on a fix that would space out requests more but if you are really making a lot of requests you would be better off using the standalone IEDB tools.

**Comment by shulanmayo** [comment] 2017-02-22 19:56
Thanks. I am willing to try both options since PI needs the results for her R1 grant soon. I will contact IEDB as well as re-install the tool. Thanks for the work!

**Comment by susannasiebert** [comment] 2017-02-22 20:01
Your local installation of the IEDB tool is fine, no need to reinstall that. I suspect that something about your pVAC-Seq install if wonky since it's still showing the behavior from a previous version that has since been fixed and I cannot reproduce the error on my part with my install of 4.0.6. Even if the IEDB API worked for you right now, pVAC-Seq would still throw the same error with the results. Can you please email me the output folder from the failed run? That should help me confirm that this is what is going on.

**Comment by shulanmayo** [comment] 2017-02-22 20:09
Sure. I sent the output from a separate email. We used old version before. Worked good until hit an issue with IEDB seq entry, so we decided to upgrade it to 4.0.6. the upgrade command possibly didn’t work out. Please let me know if you didn’t get output file. thanks

**Comment by susannasiebert** [comment] 2017-02-23 14:41
@shulanmayo I found the cause of this error. For some reason, when you are running pVAC-Seq with a local install it outputs a few additional lines at the beginning of the file. Your `MHC_Class_I/tmp/test.ann.HLA-A\*02\:01.8.tsv_1-200` looks like this:

```

**Comment by shulanmayo** [comment] 2017-02-23 15:20
I think I know what is going on.  When we initially tested the new version with local iedb install, it runs interactively. However, when I run with qsub or with background mode, prediction.py (2.7) grasps a blank argument at the end and returned non-zero exit status 2. We found this thread http://stackoverflow.com/questions/26661804/shell-variables-in-qsub

args = filter(None, args) #strip blank arguments that might be introduced by LSF

these lines might be added during our debug. I will check if it is the case. thanks

**Comment by susannasiebert** [comment] 2017-02-23 15:23
That would make sense. I'm also pretty close to having a pull request that would strip out those lines. I will probably add this change either way to make our software more robust.

**Comment by susannasiebert** [comment] 2017-03-01 15:48
The newest release (4.0.7) adds a fix for IEDB outputs with additional lines. It also fixes the "Input sequence is too short" error. Please upgrade your install of pVAC-Seq and let me know if that fixes it for you.

**Closed** 2017-03-07 13:51 UTC
