### ISSUE TITLE
Error with --iedb-install-directory

### ISSUE THREAD

**Issue by namsyvo** [griffithlab/pVAC-Seq#287] opened 2017-03-22 21:57 UTC
Hi,
I got an error when running the following command (everything is fine if I don't use option --iedb-install-directory). Can you check to see why? Thank you.

> OS: Mac OS Sierra, Version 10.12.3
> Python original version: 2.7.13
> Python with Anaconda: 3.5.2
> pVAC-Seq and local IEDB installation was set up follow the guideline in http://pvac-seq.readthedocs.io/en/v4.0.8/install.html
> 

`$pvacseq run _data/pvacseq/PCA.variant_effect.vcf "PCA" HLA-B*15:172 NetMHCpan _data/pvacseq/PCA/test -e 11 --iedb-install-directory _tools/
`
Executing MHC Class I predictions
Converting VCF to TSV
TSV file already exists. Skipping.
Splitting TSV into smaller chunks
Splitting TSV into smaller chunks - Entries 1-11
Split TSV file for Entries 1-11 already exists. Skipping.
Completed
Generating Variant Peptide FASTA and Key Files
Split FASTA file for Entries 1-22 already exists. Skipping.
Completed
Processing entries for Allele HLA-B*15:172 and Epitope Length 11 - Entries 1-22
Running IEDB on Allele HLA-B*15:172 and Epitope Length 11 with Method NetMHCpan - Entries 1-22
Traceback (most recent call last):
  File "_tools/mhc_i/src/predict_binding.py", line 378, in <module>
    Prediction().main()
  File "_tools/mhc_i/src/predict_binding.py", line 370, in main
    self.commandline_input(args)
  File "_tools/mhc_i/src/predict_binding.py", line 74, in commandline_input
    table_rows = self.format_binding(input, mhc_scores, method, use_cutoff, cutoff_value)
  File "_tools/mhc_i/src/predict_binding.py", line 124, in format_binding
    self.add_rows_binding(allele, length, proteins, score, actual_methods_used, cutoff, value)
  File "_tools/mhc_i/src/predict_binding.py", line 129, in add_rows_binding
    for (k, prediction) in enumerate(predictions):
TypeError: 'NoneType' object is not iterable
Traceback (most recent call last):
  File "/Users/namsyvo/anaconda/bin/pvacseq", line 11, in <module>
    sys.exit(main())
  File "/Users/namsyvo/anaconda/lib/python3.6/site-packages/pvacseq/pvacseq.py", line 84, in main
    args[0].func.main(args[1])
  File "/Users/namsyvo/anaconda/lib/python3.6/site-packages/pvacseq/lib/main.py", line 285, in main
    pipeline.execute()
  File "/Users/namsyvo/anaconda/lib/python3.6/site-packages/pvacseq/lib/pipeline.py", line 256, in execute
    split_parsed_output_files = self.call_iedb_and_parse_outputs(chunks)
  File "/Users/namsyvo/anaconda/lib/python3.6/site-packages/pvacseq/lib/pipeline.py", line 378, in call_iedb_and_parse_outputs
    '-e', self.iedb_executable,
  File "/Users/namsyvo/anaconda/lib/python3.6/site-packages/pvacseq/lib/call_iedb.py", line 60, in main
    response = run(prediction_class_object.iedb_executable_params(args), stdout=PIPE, check=True)
  File "/Users/namsyvo/anaconda/lib/python3.6/subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['python2.7', '_tools/mhc_i/src/predict_binding.py', 'netmhcpan', 'HLA-B*15:172', '11', '_data/pvacseq/PCA/test/MHC_Class_I/tmp/PCA_21.fa.split_1-22']' returned non-zero exit status 1.

**Comment by susannasiebert** [comment] 2017-03-22 22:04
Hi,

Would it be possible for you to attach the `_data/pvacseq/PCA/test/MHC_Class_I/tmp/PCA_21.fa.split_1-22` file? Otherwise I won't be able to debug why IEDB is throwing this error.

Thanks,
Susanna

**Comment by namsyvo** [comment] 2017-03-22 22:13
Hi, here is the file you mentioned (I added the extension .txt to be able to upload). Thanks.
[PCA_21.fa.split_1-22.txt](https://github.com/griffithlab/pVAC-Seq/files/863070/PCA_21.fa.split_1-22.txt)

**Comment by susannasiebert** [comment] 2017-03-22 22:32
Which version of IEDB do you have installed, i.e. what was the name of the tar package before you unpacked it for installation? You can also find this information in the README (mhc_i/README).

**Comment by namsyvo** [comment] 2017-03-22 22:34
Here are 2 files I used:
IEDB_MHC_I-2.15.4.tar.gz
IEDB_MHC_II-2.16.tar.gz

**Comment by susannasiebert** [comment] 2017-03-23 13:54
I was able to reproduce the error with IEDB MHC I 2.15.4. The error does not occur with IEDB MHC I 2.15.3. I suggest placing a helpdesk ticket with IEDB at help.iedb.org and send them the PCA_21.fa.split_1-22 fasta file.

**Comment by namsyvo** [comment] 2017-03-23 14:40
Thank you. In the meantime, could you share with me the IEDB data version 2.15.3 to test? I need to do some analyses soon as well. Thanks.

**Comment by susannasiebert** [comment] 2017-03-23 14:46
Do you mean the IEDB tool itself or the result from running IEDB 2.15.3 on your file? I only ran IEDB, not the whole pVAC-Seq pipeline so I don't have a pVAC-Seq output, just the IEDB output.

**Comment by namsyvo** [comment] 2017-03-23 14:49
Yes, I meant the IEDB tool (the tar package, something like IEDB_MHC_I-2.15.3.tar.gz). Thanks.

**Comment by susannasiebert** [comment] 2017-03-23 14:54
It's 240MB. I can only attach files that are smaller than 10MB. This is probably even too large for email. I haven't been able to figure out a way to download old versions from IEDB directly. Maybe you can ask on your IEDB helpdesk ticket for a way to download the old archives.

**Comment by namsyvo** [comment] 2017-03-23 14:56
Could you share with me through, e.g, google drive or dropbox or other means? I'm gonna ask IEDB as well. Thanks.

**Comment by susannasiebert** [comment] 2017-03-23 15:04
I'm hesitant to do so since the NetMHC license agreement prohibits redistribution.

You can use pVAC-Seq without the iedb install directory option for your analyses. Since your file doesn't contain many variants this shouldn't cause a problem.

**Comment by chrisamiller** [comment] 2017-03-23 15:06
Sorry, we can't redistribute the IEDB software, per their license agreement:

> The user and any research assistants, co-workers or other workers who
> may use the Software agree to not give the program to third parties or
> grant licenses on software, which include the Software, alone or
> integrated into other software, to third parties.

**Comment by namsyvo** [comment] 2017-03-23 15:06
Thank you, I'll contact IEDB. That's an example, my whole data are very large. Thanks again for your help.

**Comment by namsyvo** [comment] 2017-03-24 23:19
Hi Susanna,
I already got the old version from IEDB (IEDB_MHC_I-2.15.3.tar.gz) and setup it again. However, I still got the same error. Don't know why, because you said you tested it successfully with this version.

Here is Python versions I used:
Original:
...$ python -V
Python 2.7.13

Conda:
(py35) ...$python -V
Python 3.5.2 :: Anaconda 4.3.1 (x86_64)
(py35) ...$ which python
.../anaconda/envs/py35/bin/python

**Comment by susannasiebert** [comment] 2017-03-27 13:25
I'm not sure either. I think the IEDB folks would be better suited to help you with this problem.

**Comment by susannasiebert** [comment] 2017-03-27 13:46
I tested my version of IEDB 2.15.3 again and I'm still able to get the results. The way I tested is, is that I called IEDB directly, like so:
```
python mhc_i_2.15.3/src/predict_binding.py netmhcpan HLA-B*15:172 11 PCA_21.fa.split_1-22.txt
```
I also called it from inside my python 3.5.2. conda environment by invoking the command with  `python2.7` instead of `python` which also worked for me.

Did you uninstall (delete) IEDB 2.15.4 before installing 2.15.3? Both will try to unpack to the same mhc_i directory so maybe it didn't really unpack or it didn't overwrite existing files. I would maybe delete your existing installations or install to a clean location just to make sure. Aside from this possibility I have no idea why it would work for me and not for you.

**Comment by namsyvo** [comment] 2017-03-27 18:32
Yes, actually I did all what you suggested before. Don't know why the error still happens. I'll contact IEDB to figure out why. Thank you for your help.

**Comment by chrisamiller** [comment] 2017-03-27 19:44
FWIW, I was having the same error, and downgrading to 2.15.3 worked for me. It may be worth banging on it a little more on your end.

**Comment by namsyvo** [comment] 2017-03-28 18:57
Hi Susanna and Chris,
I talked to IEDB guys and they said that the problems might be related to Mac OS. Unfortunately the IEDB tool only run on Linux at this time. pVAC-Seq with IEDB local installation also works well on our cluster. So I guess that's exact problem. I think you can notice users about this. Thank you very much for you help.

**Comment by susannasiebert** [comment] 2017-03-28 19:07
That's good to know. Thanks for passing it along. I will make a note to update our documentation with this information. I will close this issue.

**Closed by susannasiebert** 2017-03-28 19:07 UTC
