### ISSUE TITLE
Good predictions are filtered out

### ISSUE THREAD

**Issue by strixeh** [griffithlab/pVAC-Seq#120] opened 2016-07-26 20:42 UTC
Hi, it is me again :).

I just ran the pvacseq pipeline from start to finish now. It all works fine except that the _filtered.tsv does not contain all the peptides with passing my filter. I ran `pvacseq run /home/strix/pvacseq/input/claire_anno.vcf clairerealtest H-2-Ld,H-2-Kd 8,9,10,11 NetMHC NetMHCcons NetMHCpan PickPocket SMM SMMPMBEC /home/strix/pvacseq/output/clairerealtest -m lowest -b 1000` to try it all. 

`clairerealtest_filtered.tsv` contains the following lines: 

```
Chromosome	Start	Stop	Reference	Variant	Transcript	Ensembl Gene ID	Variant Type	Mutation	Protein Position	Gene Name	HLA Allele	Peptide Length	Sub-peptide Position	MT Epitope Seq	WT Epitope Seq	Best MT Score	Corresponding WT Score	Fold Change	Best MT Score Method	Median MT Score All Methods	NetMHC WT Score	NetMHC MT Score	NetMHCcons WT Score	NetMHCcons MT Score	NetMHCpan WT Score	NetMHCpan MT Score	PickPocket WT Score	PickPocket MT Score	SMM WT Score	SMM MT Score	SMMPMBEC WT Score	SMMPMBEC MT Score
6	135078912	135078913	C	A	ENSMUST00000050104	ENSMUSG00000046733	missense	F/L	119	Gprc5a	H-2-Kd	11	9	HALNLIKLVRG	HAFNLIKLVRG	173.66	147.81	0.851	SMMPMBEC	33801.62	33341	32044	35176.57	35559.24	36736.78	39575.9	50000	50000	484.04	342.67	147.81	173.66
6	128489119	128489120	C	T	ENSMUST00000112132	ENSMUSG00000030359	missense	G/E	1199	Pzp	H-2-Kd	11	3	DSLHWQRPEDV	DSLHWQRPGDV	459.95	414.68	0.902	SMMPMBEC	27918.475	26263	25276	31060.99	30560.95	36786.5	37044.52	50000	50000	2022.46	2079.12	414.68	459.95
12	33958478	33958479	C	A	ENSMUST00000049089	ENSMUSG00000035799	missense	Q/K	168	Twist1	H-2-Kd	9	6	LYQVLKSDE	LYQVLQSDE	99.33	124.66	1.255	PickPocket	2604.025	7381	4866	13356.59	11112.54	24306.5	25271.13	124.66	99.33	218.91	141.99	429.63	342.05
3	152455902	152455903	A	T	ENSMUST00000089982	ENSMUSG00000039068	missense	K/N	811	Zzz3	H-2-Kd	11	8	KKQNLQQMQAE	KKQKLQQMQAE	503.16	4443.34	8.831	SMMPMBEC	17694.55	30709	30662	36141.06	36337.11	42298.01	42800.27	4625.9	4727.1	6150.07	1380	4443.34	503.16
3	152455902	152455903	A	T	ENSMUST00000106100	ENSMUSG00000039068	missense	K/N	812	Zzz3	H-2-Kd	11	8	KKQNLQQMQAE	KKQKLQQMQAE	503.16	4443.34	8.831	SMMPMBEC	17694.55	30709	30662	36141.06	36337.11	42298.01	42800.27	4625.9	4727.1	6150.07	1380	4443.34	503.16
3	152455902	152455903	A	T	ENSMUST00000106101	ENSMUSG00000039068	missense	K/N	812	Zzz3	H-2-Kd	11	8	KKQNLQQMQAE	KKQKLQQMQAE	503.16	4443.34	8.831	SMMPMBEC	17694.55	30709	30662	36141.06	36337.11	42298.01	42800.27	4625.9	4727.1	6150.07	1380	4443.34	503.16
3	152455902	152455903	A	T	ENSMUST00000106103	ENSMUSG00000039068	missense	K/N	311	Zzz3	H-2-Kd	11	8	KKQNLQQMQAE	KKQKLQQMQAE	503.16	4443.34	8.831	SMMPMBEC	17694.55	30709	30662	36141.06	36337.11	42298.01	42800.27	4625.9	4727.1	6150.07	1380	4443.34	503.16
3	152455902	152455903	A	T	ENSMUST00000200570	ENSMUSG00000039068	missense	K/N	315	Zzz3	H-2-Kd	11	8	KKQNLQQMQAE	KKQKLQQMQAE	503.16	4443.34	8.831	SMMPMBEC	17694.55	30709	30662	36141.06	36337.11	42298.01	42800.27	4625.9	4727.1	6150.07	1380	4443.34	503.16
```
However, when I look in the `clairerealtest.combined.parsed.tsv`, I find that the best predicted peptide is:
```
Chromosome	Start	Stop	Reference	Variant	Transcript	Ensembl Gene ID	Variant Type	Mutation	Protein Position	Gene Name	HLA Allele	Peptide Length	Sub-peptide Position	MT Epitope Seq	WT Epitope Seq	Best MT Score	Corresponding WT Score	Fold Change	Best MT Score Method	Median MT Score All Methods	NetMHC WT Score	NetMHC MT Score	NetMHCcons WT Score	NetMHCcons MT Score	NetMHCpan WT Score	NetMHCpan MT Score	PickPocket WT Score	PickPocket MT Score	SMM WT Score	SMM MT Score	SMMPMBEC WT Score	SMMPMBEC MT Score
12	33958478	33958479	C	A	ENSMUST00000049089	ENSMUSG00000035799	missense	Q/K	168	Twist1	H-2-Kd	10	6	LYQVLKSDEL	LYQVLQSDEL	133.03	87.23	0.656	PickPocket	332.615	550	412	273.16	253.23	135.88	154.82	87.23	133.03	1684.46	1703.96	1512.31	876.27
```
 
So, in the filtered file, the peptide with length 9 from that specific chr loc is included, but not the one with length 10 which has the best score. 

When I run only `pvacseq run /home/strix/pvacseq/input/claire_anno.vcf clairerealtest H-2-Ld 10 NetMHC /home/strix/pvacseq/output/clairerealtest -m lowest -b 1000` that specific peptide with length 10 showes up in both the filtered file and in the parsed combined file.

I noticed my computer slowed down pretty hard when running the pipeline. I am not sure if this is related. 

Any ideas?

Best,
Nils

**Comment by susannasiebert** [comment] 2016-07-26 21:20
Hi Nils,

Unfortunately, I wasn't able to reproduce this issue locally. What I did is take your missing best peptide and run it manually through `pvacseq binding_filter`. I also tried it with a file that contains both `12  33958478    33958479` entries in case they somehow conflict with each other but both files are being kept, as expected.

When you did the first full run, did you see all of the following status messages:
> Running Binding Filters
> Completed
> Done: pvacseq has completed. File /home/strix/pvacseq/output/clairerealtest/clairerealtest_filtered.tsv contains list of binding-filtered putative neoantigens
> We recommend appending coverage information and running `pvacseq coverage_filter` to filter based on sequencing coverage information

If you didn't than it might be the case that the run was aborted while the binding filter was running. Maybe your machine ran out of memory. Could you please try and run your full `clairerealtest.combined.parsed.tsv` file manually through `pvacseq binding_filter` and see if the output contains both entries for `12  33958478    33958479`?

**Comment by susannasiebert** [comment] 2016-07-26 21:29
Also, the peptide with length 9 has a Best MT Score of 99.33 and the one with length 10 has a score of 133.03. So wouldn't the former be the better of the two since the Best MT Score is lower? It still doesn't explain why the latter is getting filtered out since it's well below the binding filter threshold of 1000 that you picked.

**Comment by strixeh** [comment] 2016-07-26 22:11
Hi, and again, thanks for the quick and good help. 

Yes, pvacseq produced the following status messages:
```
Running Binding Filters
Completed
Done: pvacseq has completed. File /home/strix/pvacseq/output/clairerealtest/clairerealtest_filtered.tsv contains list of binding-filtered putative neoantigens
We recommend appending coverage information and running `pvacseq coverage_filter` to filter based on sequencing coverage information
```
I tried running the pvacseq binding_filter and it gets weird. `pvacseq binding_filter /home/strix/pvacseq/output/clairerealtest/clairerealtest.combined.parsed.tsv /home/strix/pvacseq/output/clairerealtest/clairerealtest_filtered_2nd.tsv -m lowest -b 1000` reproduces what i got when i ran the whole pipeline.
```
Chromosome	Start	Stop	Reference	Variant	Transcript	Ensembl Gene ID	Variant Type	Mutation	Protein Position	Gene Name	HLA Allele	Peptide Length	Sub-peptide Position	MT Epitope Seq	WT Epitope Seq	Best MT Score	Corresponding WT Score	Fold Change	Best MT Score Method	Median MT Score All Methods	NetMHC WT Score	NetMHC MT Score	NetMHCcons WT Score	NetMHCcons MT Score	NetMHCpan WT Score	NetMHCpan MT Score	PickPocket WT Score	PickPocket MT Score	SMM WT Score	SMM MT Score	SMMPMBEC WT Score	SMMPMBEC MT Score
6	135078912	135078913	C	A	ENSMUST00000050104	ENSMUSG00000046733	missense	F/L	119	Gprc5a	H-2-Kd	11	9	HALNLIKLVRG	HAFNLIKLVRG	173.66	147.81	0.851	SMMPMBEC	33801.62	33341	32044	35176.57	35559.24	36736.78	39575.9	50000	50000	484.04	342.67	147.81	173.66
6	128489119	128489120	C	T	ENSMUST00000112132	ENSMUSG00000030359	missense	G/E	1199	Pzp	H-2-Kd	11	3	DSLHWQRPEDV	DSLHWQRPGDV	459.95	414.68	0.902	SMMPMBEC	27918.475	26263	25276	31060.99	30560.95	36786.5	37044.52	50000	50000	2022.46	2079.12	414.68	459.95
12	33958478	33958479	C	A	ENSMUST00000049089	ENSMUSG00000035799	missense	Q/K	168	Twist1	H-2-Kd	9	6	LYQVLKSDE	LYQVLQSDE	99.33	124.66	1.255	PickPocket	2604.025	7381	4866	13356.59	11112.54	24306.5	25271.13	124.66	99.33	218.91	141.99	429.63	342.05
3	152455902	152455903	A	T	ENSMUST00000089982	ENSMUSG00000039068	missense	K/N	811	Zzz3	H-2-Kd	11	8	KKQNLQQMQAE	KKQKLQQMQAE	503.16	4443.34	8.831	SMMPMBEC	17694.55	30709	30662	36141.06	36337.11	42298.01	42800.27	4625.9	4727.1	6150.07	1380	4443.34	503.16
3	152455902	152455903	A	T	ENSMUST00000106100	ENSMUSG00000039068	missense	K/N	812	Zzz3	H-2-Kd	11	8	KKQNLQQMQAE	KKQKLQQMQAE	503.16	4443.34	8.831	SMMPMBEC	17694.55	30709	30662	36141.06	36337.11	42298.01	42800.27	4625.9	4727.1	6150.07	1380	4443.34	503.16
3	152455902	152455903	A	T	ENSMUST00000106101	ENSMUSG00000039068	missense	K/N	812	Zzz3	H-2-Kd	11	8	KKQNLQQMQAE	KKQKLQQMQAE	503.16	4443.34	8.831	SMMPMBEC	17694.55	30709	30662	36141.06	36337.11	42298.01	42800.27	4625.9	4727.1	6150.07	1380	4443.34	503.16
3	152455902	152455903	A	T	ENSMUST00000106103	ENSMUSG00000039068	missense	K/N	311	Zzz3	H-2-Kd	11	8	KKQNLQQMQAE	KKQKLQQMQAE	503.16	4443.34	8.831	SMMPMBEC	17694.55	30709	30662	36141.06	36337.11	42298.01	42800.27	4625.9	4727.1	6150.07	1380	4443.34	503.16
3	152455902	152455903	A	T	ENSMUST00000200570	ENSMUSG00000039068	missense	K/N	315	Zzz3	H-2-Kd	11	8	KKQNLQQMQAE	KKQKLQQMQAE	503.16	4443.34	8.831	SMMPMBEC	17694.55	30709	30662	36141.06	36337.11	42298.01	42800.27	4625.9	4727.1	6150.07	1380	4443.34	503.16
```
However, `pvacseq binding_filter /home/strix/pvacseq/output/clairerealtest/clairerealtest.combined.parsed.tsv /home/strix/pvacseq/output/clairerealtest/clairerealtest_filtered_2nd.tsv -m median -b 1000` gives me only the peptide with length 10, as it should be since this is the only peptide that pass median score of 1000:
```
Chromosome	Start	Stop	Reference	Variant	Transcript	Ensembl Gene ID	Variant Type	Mutation	Protein Position	Gene Name	HLA Allele	Peptide Length	Sub-peptide Position	MT Epitope Seq	WT Epitope Seq	Best MT Score	Corresponding WT Score	Fold Change	Best MT Score Method	Median MT Score All Methods	NetMHC WT Score	NetMHC MT Score	NetMHCcons WT Score	NetMHCcons MT Score	NetMHCpan WT Score	NetMHCpan MT Score	PickPocket WT Score	PickPocket MT Score	SMM WT Score	SMM MT Score	SMMPMBEC WT Score	SMMPMBEC MT Score
12	33958478	33958479	C	A	ENSMUST00000049089	ENSMUSG00000035799	missense	Q/K	168	Twist1	H-2-Kd	10	6	LYQVLKSDEL	LYQVLQSDEL	133.03	87.23	0.656	PickPocket	332.615	550	412	273.16	253.23	135.88	154.82	87.23	133.03	1684.46	1703.96	1512.31	876.27
```

Regarding the 9 or 10 AA long peptide. We have actually been using the 10 AA long WT peptide as a control peptide in our experiments, and know that it has good binding. We wanted to run it through the pipeline, to see the predictions from all algorithms together. Also, its mostly PickPocket that drives the good MT score for the 99 AA long peptide whereas the 10 AA long peptide has good predicted score in most algorithms.

**Comment by strixeh** [comment] 2016-07-26 22:33
So I might have figured it out. When I read https://github.com/griffithlab/pVAC-Seq it says: 

> The ‘best candidate’ (lowest MT binding score) per mutation is chosen across all specified k-mers that were installed as input.

Is this what is happening? Since 'lowest' gives the 9 AA peptide, and 'median' gives the 10 AA peptide, one or the other is always filtered it out?

**Comment by susannasiebert** [comment] 2016-07-27 13:44
You're right. There is some remnant of code in the binding filter that picks the best candidate per gene. However, this code should be removed because we added the `--top-result-per-mutation` flag which would only keep the top peptide per allele and per peptide length for each variant. If the flag isn't set (like in your run) than we should keep all variants. We don't really want the binding filter to do any additional filtering aside from binding affinity and fold change so it was an oversight on our part that this portion of code wasn't removed.

**Comment by strixeh** [comment] 2016-07-27 15:05
Great! Thanks for baring with all my question :)!

**Comment by susannasiebert** [comment] 2016-08-02 19:01
Nils,
Can you please confirm that this issue has been fixed so that I can close it?
Thanks,
Susanna

**Comment by strixeh** [comment] 2016-08-02 20:00
I can confirm this issue have been fixed. Output in the filtered TSV:

```
Chromosome	Start	Stop	Reference	Variant	Transcript	Ensembl Gene ID	Variant Type	Mutation	Protein Position	Gene Name	HLA Allele	Peptide Length	Sub-peptide Position	MT Epitope Seq	WT Epitope Seq	Best MT Score	Corresponding WT Score	Fold Change	Best MT Score Method	Median MT Score All Methods	PickPocket WT Score	PickPocket MT Score	SMMPMBEC WT Score	SMMPMBEC MT Score
12	33958478	33958479	C	A	ENSMUST00000049089	ENSMUSG00000035799	missense	Q/K	168	Twist1	H-2-Kd	9	6	LYQVLKSDE	LYQVLQSDE	99.33	124.66	1.255	PickPocket	220.69	124.66	99.33	429.63	342.05
12	33958478	33958479	C	A	ENSMUST00000049089	ENSMUSG00000035799	missense	Q/K	168	Twist1	H-2-Kd	10	6	LYQVLKSDEL	LYQVLQSDEL	133.03	87.23	0.656	PickPocket	504.65	87.23	133.03	1512.31	876.27
```

Thank you so much!

**Comment by susannasiebert** [comment] 2016-08-02 20:00
Great. I'll resolve this issue.

**Closed by susannasiebert** 2016-08-02 20:00 UTC
